name = "pollinations-auth"
main = "src/index.ts"
compatibility_date = "2025-08-01"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 3000

[assets]
not_found_handling = "single-page-application"
run_worker_first = [ "/api/*" ]

[[d1_databases]]
binding = "DB"
database_name = "pollinations-auth"
database_id = "cc225cad-b9a2-4595-8323-6602e7680511"
migrations_dir = "drizzle"

[vars]
ENVIRONMENT = "development"
PUBLIC_BASE_URL = "http://localhost:3000"
PUBLIC_AUTH_PATH = "/api/auth"
POLAR_SUCCESS_URL = "http://localhost:3000"

[env.staging]
route = { pattern = "staging.pollinations.ai/*", zone_name = "pollinations.ai" }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "pollinations-auth-staging"
database_id = "dbd3274b-92ac-45d3-a07a-b070eb212654"
migrations_dir = "drizzle"

[env.staging.vars]
ENVIRONMENT = "staging"
PUBLIC_BASE_URL = "https://staging.pollinations.ai"
PUBLIC_AUTH_PATH = "/api/auth"
POLAR_SUCCESS_URL = "https://staging.pollinations.ai"

[triggers]
crons = [ "* * * * *" ] # Trigger every minute

[env.production]
route = { pattern = "beta.pollinations.ai/*", zone_name = "pollinations.ai" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "pollinations-auth"
database_id = "cc225cad-b9a2-4595-8323-6602e7680511"
migrations_dir = "drizzle"

[env.production.vars]
ENVIRONMENT = "production"
PUBLIC_BASE_URL = "https://beta.pollinations.ai"
PUBLIC_AUTH_PATH = "/api/auth"
POLAR_SUCCESS_URL = "https://beta.pollinations.ai"

[env.test]

[[env.test.d1_databases]]
binding = "DB"
database_name = "pollinations-auth"
database_id = "cc225cad-b9a2-4595-8323-6602e7680511"

[env.test.vars]
ENVIRONMENT = "test"
BASE_URL = "http://localhost:3000"
AUTH_BASE_PATH = "/api/auth"
GITHUB_CLIENT_ID = "test_github_client_id"
GITHUB_CLIENT_SECRET = "test_github_client_secret"
POLAR_ACCESS_TOKEN = "test_polar_token"
POLAR_SUCCESS_URL = "http://localhost:3000/success"
