name = "pollinations-auth"
main = "src/index.ts"
compatibility_date = "2025-08-01"
compatibility_flags = [ "nodejs_compat", "nodejs_als" ]

[dev]
port = 3000

[assets]
directory = "dist/client"
not_found_handling = "single-page-application"
run_worker_first = [ "/api/*" ]

[[d1_databases]]
binding = "DB"
database_name = "pollinations-auth"
database_id = "cc225cad-b9a2-4595-8323-6602e7680511"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "0d4a093f99474344b6fc72492c1ffba9"

[vars]
ENVIRONMENT = "development"
PUBLIC_BASE_URL = "http://localhost:3000"
PUBLIC_AUTH_PATH = "/api/auth"
POLAR_SUCCESS_URL = "http://localhost:3000"
POLAR_SERVER = "sandbox"
TINYBIRD_INGEST_URL = "http://localhost:7181/v0/events?name=generation_event"

[env.staging]
route = { pattern = "staging.pollinations.ai/*", zone_name = "pollinations.ai" }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "pollinations-auth-staging"
database_id = "dbd3274b-92ac-45d3-a07a-b070eb212654"
migrations_dir = "drizzle"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "0d4a093f99474344b6fc72492c1ffba9"

[env.staging.vars]
ENVIRONMENT = "staging"
PUBLIC_BASE_URL = "https://enter.pollinations.ai"
PUBLIC_AUTH_PATH = "/api/auth"
POLAR_SUCCESS_URL = "https://enter.pollinations.ai"
POLAR_SERVER = "sandbox"
TINYBIRD_INGEST_URL = "https://api.tinybird.co/v0/events?name=generation_event"

[triggers]
crons = [ "* * * * *" ] # Trigger every minute

[env.production]
route = { pattern = "beta.pollinations.ai/*", zone_name = "pollinations.ai" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "pollinations-auth"
database_id = "cc225cad-b9a2-4595-8323-6602e7680511"
migrations_dir = "drizzle"

[[env.production.kv_namespaces]]
binding = "KV"
id = "0d4a093f99474344b6fc72492c1ffba9"

[env.production.vars]
ENVIRONMENT = "production"
PUBLIC_BASE_URL = "https://enter.pollinations.ai"
PUBLIC_AUTH_PATH = "/api/auth"
POLAR_SUCCESS_URL = "https://enter.pollinations.ai"
POLAR_SERVER = "production"
TINYBIRD_INGEST_URL = "https://api.tinybird.co/v0/events?name=generation_event"

[env.test]

[[env.test.d1_databases]]
binding = "DB"
database_name = "pollinations-auth"
database_id = "cc225cad-b9a2-4595-8323-6602e7680511"
migrations_dir = "drizzle"

[env.test.vars]
ENVIRONMENT = "test"
PUBLIC_BASE_URL = "http://localhost:3000"
PUBLIC_AUTH_PATH = "/api/auth"
GITHUB_CLIENT_ID = "test_github_client_id"
GITHUB_CLIENT_SECRET = "test_github_client_secret"
POLAR_ACCESS_TOKEN = "test_polar_token"
POLAR_SUCCESS_URL = "http://localhost:3000"
POLAR_SERVER = "sandbox"
TINYBIRD_INGEST_URL = "http://localhost:7181/v0/events?name=generation_event"
