# Cloudflare Pages configuration
name = "pollinations-pitch"
compatibility_date = "2023-05-01"

# This is the key setting needed for Pages
pages_build_output_dir = "dist"

# Note: Custom domains are configured in the Cloudflare dashboard
# after deployment, not in the wrangler.toml file