name = "pollinations-text-cache"
main = "src/index.js"
compatibility_date = "2023-05-18"

# R2 bucket for text storage
[[r2_buckets]]
binding = "TEXT_BUCKET"
bucket_name = "pollinations-text"

# Environment variables
[vars]
ORIGIN_HOST = "text-origin.pollinations.ai"
#ORIGIN_HOST ="http://163.172.149.24:16385"
# Enable debug logging (set to "true" to enable, "false" to disable)
DEBUG = "cache:*"

# GA4 Analytics (secrets set via: wrangler secret put GA_MEASUREMENT_ID)
GA_MEASUREMENT_ID = ""
GA_API_SECRET = ""

# Increase limits for long-running operations
# This requires a paid Workers Unbound plan
[limits]
cpu_ms = 30000  # 30 seconds CPU time (max for Workers Unbound)

# Configure logging
[observability]
enabled = true      # Enable logs for local development

[observability.logs]
invocation_logs = true

# ===========================================
# ENVIRONMENT SETUP INSTRUCTIONS
# ===========================================
# This configuration uses environment variables from the .env file.
# Make sure your .env file in the root directory includes:
#
# GA_MEASUREMENT_ID=your-ga-measurement-id
# GA_API_SECRET=your-ga-api-secret
# CLOUDFLARE_ACCOUNT_ID=your-cloudflare-account-id
#
# The deploy.sh script will automatically create a .dev.vars file
# for local development using these values.
# ===========================================