# This is a basic workflow to help you get started with Actions

name: Post CID to social

# Controls when the workflow will run
on:
  repository_dispatch:
    types: post-social
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  post-socal:
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Publishes to IPFS and returns CID in  ${{ steps.ipfs.outputs.hash }}
      - name: Check out pollinations repository code
        uses: actions/checkout@v2
      - name: Post to social media
        run: 'node  ${{ github.workspace }}/app/dist/social-post.js ${{ github.event.client_payload.platform }} ${{ github.event.client_payload.cid }}"'



 