blank_issues_enabled: false
contact_links:
  - name: Pollinations Community Support
    url: https://discord.gg/pollinations
    about: Join our Discord community for general questions and discussions