name: New Issue Labeler
on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Debug association
        run: |
          echo "author_association=${{ github.event.issue.author_association }}"

      # Outside collaborator
      - name: Label collab-issue
        if: ${{ github.event.issue.author_association == 'COLLABORATOR' }}
        uses: actions/github-script@v7
        with:
          script: |
            const current = (context.payload.issue.labels || []).map(l => l.name);
            if (!current.includes("collab-issue")) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: ["collab-issue"]
              });
            }

      # Everyone else who is NOT MEMBER/OWNER/COLLABORATOR
      - name: Label ext-issue
        if: ${{ !contains(fromJson('["MEMBER","OWNER","COLLABORATOR"]'), github.event.issue.author_association) }}
        uses: actions/github-script@v7
        with:
          script: |
            const current = (context.payload.issue.labels || []).map(l => l.name);
            if (!current.includes("ext-issue")) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: ["ext-issue"]
              });
            }
