model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_base: https://pollinations.openai.azure.com/
      api_version: "2024-08-01-preview"
      api_key: os.environ/AZURE_OPENAI_API_KEY # The `os.environ/` prefix tells litellm to read this from the env

litellm_settings:
  drop_params: True
